create schema PENJUALANDVD;

use PENJUALANDVD;

create table MOVIE (
 	KODE_DVD VARCHAR(10) primary key,
 	JUDUL VARCHAR(60),
 	HARGA_SEWA DOUBLE,
 	DENDA DOUBLE,
 	TAHUN_RILIS YEAR(4)
);

create table GENRE (
	ID_GENRE smallint primary key,
	GENRE VARCHAR(45)
);

create table GENRE_MOVIE (
    ID_GENRE smallint REFERENCES GENRE(ID_GENRE),
    KODE_DVD VARCHAR(10) REFERENCES MOVIE(KODE_DVD)
);

create table KECAMATAN (
	ID_KECAMATAN smallint primary key,
	KECAMATAN VARCHAR(45)
);

create table KELURAHAN(
	ID_KELURAHAN smallint primary key,
	KELURAHAN VARCHAR(45),
	ID_KECAMATAN smallint references KECAMATAN(ID_KECAMATAN)
);

create table PELANGGAN (
	KODE_PELANGGAN VARCHAR(10) primary key,
	NAMA VARCHAR(45),
	ALAMAT VARCHAR(60),
	JENIS_KELAMIN CHAR(1),
	ID_KELURAHAN SMALLINT references KELURAHAN(ID_KELURAHAN)
);

create table KONTAK_PELANGGAN (
	NO_HP VARCHAR(25) unique,
	KODE_PELANGGAN VARCHAR(10) references PELANGGAN(KODE_PELANGGAN)
);

create table TRANSAKSI (
	TANGGAL_SEWA DATE not null primary key,
	TANGGAL_WAJIB_KEMBALI DATE,
	TANGGAL_REALISASI_KEMBALI DATE,
	KODE_DVD VARCHAR(10) REFERENCES MOVIE(KODE_DVD),
	KODE_PELANGGAN VARCHAR(10) REFERENCES PELANGGAN(KODE_PELANGGAN)
);


alter table MOVIE
modify TAHUN_RILIS YEAR(4);

alter table PELANGGAN add constraint CK_JENIS_KELAMIN check (JENIS_KELAMIN in ('P', 'L'));